name: Mobs
version: 1.5.1 b3
author: coldandtired
main: me.coldandtired.mobs.Mobs
description: THE mob plugin
website: coldandtired.binhoster.com
softdepend: [Vault, SpoutPlugin, TerrainControl]
depend: [Extra Events]
commands:
    reload_mobs:
        description: Reload the config without reloading the plugin itself
        aliases: rm
        usage: "Usage: /reload_mobs"
        permission: mobs.can_reload_config      
permissions:
    mobs.can_reload_config:
        description: Allows a user to reload the config
        default: op