name: Mobs
version: Beta4
author: coldandtired
main: me.coldandtired.mobs.Mobs
description: THE mob plugin
softdepend: [Vault, WorldGuard, TerrainControl, Heroes, SpoutPlugin]
commands:
    reload_mobs:
        description: Reload the config without reloading the plugin itself
        aliases: rm
        usage: "Usage: /reload_mobs"
        permission: mobs.can_reload_mobs      
    repeating_outcomes:
        description: Adjust the repeating part of the plugin
        aliases: ro
        usage: "Usage: /repeating_outcomes [enable|disable|pause|unpause|check|set_interval] [seconds] [name]"
        permission: mobs.can_change_repeating_outcomes
permissions:
    mobs.can_reload_mobs:
        description: Allows reloading of the config
        default: op
    mobs.can_change_repeating_outcomes:
        description: Allows reloading of the config
        default: op