name: Mobs
version: 1.6.4 b1
author: coldandtired
main: eu.sylian.mobs.Mobs
description: THE mob plugin
website: sylian.eu
softdepend: [Vault, SpoutPlugin, TerrainControl]
depend: [Extra Events]
commands:
    reload_mobs:
        description: Reload the config without reloading the plugin itself
        aliases: rm
        usage: "Usage: /reload_mobs"
        permission: mobs.can_reload_config      
permissions:
    mobs.can_reload_config:
        description: Allows a user to reload the config
        default: op