package me.coldandtired.mobs.enums;

public enum MCcondition 
{
	ADULT, 
	ANGRY,
	AREA,
	//ATTACKER_TYPE
	BIOME,
	CHUNK_MOB_COUNT,
	//CAN_BREED,
	//CHUNK_MOB_COUNT,
	DEATH_CAUSE,
	//BOSS_MOB,
	KILLED_BY_PLAYER,
	//KILLER_NAME,
	LIGHT_LEVEL,
	//LOCAL_TIME,
	//LUNAR_PHASE,
	//MOB_AGE,
	NAME,
	NOT_ADULT,
	NOT_ANGRY,
	NOT_AREA,
	NOT_BIOME,
	NOT_DEATH_CAUSE,
	NOT_KILLED_BY_PLAYER,
	NOT_NAME,
	NOT_OWNER,
	NOT_POWERED,
	NOT_RAINING,
	NOT_SADDLED,
	NOT_SHEARED,
	NOT_SPAWN_REASON,
	NOT_TAMED,
	NOT_THUNDERING,
	NOT_WORLD_NAME,
	OWNER,
	//MOB_NOT_STANDING_ON,
	//MOB_STANDING_ON,
	//OCELOT_TYPE,
	//ONLINE_PLAYER_COUNT,
	//PERCENT,
	//PLAYER_HOLDING,
	//PLAYER_ITEM,
	//PLAYER_MONEY,
	//PLAYER_PERMISSION,
	//PLAYER_WEARING,
	POWERED,
	RAINING,
	//REGION_MOB_COUNT,
	//REMAINING_LIFETIME,
	SADDLED,
	SHEARED,
	SPAWN_REASON,
	TAMED,
	//owner name
	THUNDERING,
	//time conditions
	//VILLAGER_TYPE,
	//WOOL_COLORS,
	//WORLD_MOB_COUNT,
	WORLD_NAME, 
	//WORLD_PLAYER,
	WORLD_TIME,
	//WORLD_TYPE,
	X,
	Y,
	Z;
	
	public static String getXpath()
	{
		String s = "";
		for (MCcondition c : values()) s = s + " | " + c.toString().toLowerCase();
		return s.substring(3);
	}
}